package com.trading.strategy;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Timeout;

import java.lang.reflect.Method;
import java.lang.reflect.Field;
import java.util.*;

/**
 * REAL TEST for executeTradingCycle method with PRE-POPULATED HISTORICAL DATA
 * Ensures buy signals are generated by simulating proper VWAP crossover conditions
 */
@DisplayName("Real Trading Cycle Test - WITH HISTORICAL DATA")
public class RealTradingCycleTest {

    private VWAPOptionsStrategy strategy;
    private Object batchVWAPAnalyzer;
    private Object historicalDataManager;
    private List<String> executedSignals;

    @BeforeEach
    void setUp() throws Exception {
        strategy = new VWAPOptionsStrategy();
        executedSignals = new ArrayList<>();

        // Get access to BatchVWAPAnalyzer and HistoricalDataManager
        Field vwapAnalyzerField = VWAPOptionsStrategy.class.getDeclaredField("vwapAnalyzer");
        vwapAnalyzerField.setAccessible(true);
        batchVWAPAnalyzer = vwapAnalyzerField.get(strategy);

        Field historicalDataManagerField = batchVWAPAnalyzer.getClass().getDeclaredField("historicalDataManager");
        historicalDataManagerField.setAccessible(true);
        historicalDataManager = historicalDataManagerField.get(batchVWAPAnalyzer);

        System.out.println("🚀 INITIALIZED WITH HISTORICAL DATA ACCESS");

        // PRE-POPULATE HISTORICAL DATA FOR BUY SIGNALS
        prePopulateHistoricalData();
    }

    @Test
    @Timeout(300)
    @DisplayName("REAL CYCLE: Complete Trading Cycle with Historical Data")
    void testCompleteTradingCycleWithHistoricalData() throws Exception {
        System.out.println("🚀 REAL CYCLE: Complete Trading Cycle with Historical Data");
        System.out.println("=========================================================");

        // Step 1: Verify historical data is populated
        verifyHistoricalData();

        // Step 2: Execute complete trading cycle (should generate buy signals)
        executeRealTradingCycle();

        // Step 3: Verify buy signals were generated
        verifyBuySignalsGenerated();
    }

    @Test
    @Timeout(300)
    @DisplayName("REAL CYCLE: Force VWAP Crossover Buy Signal")
    void testForceVWAPCrossoverBuySignal() throws Exception {
        System.out.println("🎯 REAL CYCLE: Force VWAP Crossover Buy Signal");
        System.out.println("==============================================");

        String ceSymbol = "NFO:NIFTY25D0226250CE";
        String peSymbol = "NFO:NIFTY25D0226250PE";

        // Force perfect VWAP crossover conditions
        System.out.println("\n🔧 SETTING UP PERFECT VWAP CROSSOVER CONDITIONS...");

        // Clear existing data
        clearHistoricalData();

        // Setup historical data for PERFECT CROSSOVER
        setupPerfectCrossoverData(ceSymbol, 101.75, 102.5); // CE: Will crossover
        setupPerfectCrossoverData(peSymbol, 113.65, 114.2); // PE: Will crossover

        // Execute trading cycle - should generate buy signals for both
        executeRealTradingCycle();

        // Verify both CE and PE generated buy signals
        verifyMultipleBuySignals();
    }

    @Test
    @Timeout(240)
    @DisplayName("REAL CYCLE: VWAP Crossover Analysis with Historical Data")
    void testVWAPAnalysisWithHistoricalData() throws Exception {
        System.out.println("🎯 REAL CYCLE: VWAP Crossover Analysis with Historical Data");
        System.out.println("==========================================================");

        // Get suitable options first
        Map<String, String> selectedOptions = findRealOptions();

        if (selectedOptions.isEmpty()) {
            System.out.println("❌ No suitable options found for analysis");
            return;
        }

        // Ensure historical data is populated for selected options
        for (String option : selectedOptions.values()) {
            if (option != null) {
                ensureHistoricalData(option);
            }
        }

        // Analyze VWAP crossovers with proper historical data
        List<String> instruments = new ArrayList<>();
        if (selectedOptions.get("CE") != null) instruments.add(selectedOptions.get("CE"));
        if (selectedOptions.get("PE") != null) instruments.add(selectedOptions.get("PE"));

        System.out.println("🔍 Analyzing VWAP Crossovers with Historical Data for: " + instruments);

        Map<String, Boolean> crossoverResults = analyzeVWAPCrossovers(instruments);

        // Print analysis results
        System.out.println("\n📊 VWAP CROSSOVER ANALYSIS RESULTS (WITH HISTORICAL DATA):");
        boolean anyBuySignals = false;
        for (Map.Entry<String, Boolean> entry : crossoverResults.entrySet()) {
            String instrument = entry.getKey();
            boolean crossover = entry.getValue();
            System.out.println("   " + instrument + ": " + (crossover ? "🎯 BUY SIGNAL" : "⏸️ NO SIGNAL"));

            if (crossover) {
                anyBuySignals = true;
                executedSignals.add(instrument);
                System.out.println("   🚀 EXECUTING BUY FOR: " + instrument);
                executeRealBuySignal(instrument);
            }
        }

        if (!anyBuySignals) {
            System.out.println("⚠️  No buy signals generated - check historical data setup");
        }
    }

    @Test
    @Timeout(300)
    @DisplayName("REAL CYCLE: Multiple Instruments Buy Signal Test")
    void testMultipleInstrumentsBuySignals() throws Exception {
        System.out.println("🎯 REAL CYCLE: Multiple Instruments Buy Signal Test");
        System.out.println("===================================================");

        // Test multiple option strikes with historical data
        String[] testSymbols = {
                "NFO:NIFTY25D0226250CE",  // Your specific CE
                "NFO:NIFTY25D0226250PE",  // Your specific PE
                "NFO:NIFTY25D0226200CE",  // Nearby strike CE
                "NFO:NIFTY25D0226200PE"   // Nearby strike PE
        };

        int buySignalsGenerated = 0;

        for (String symbol : testSymbols) {
            System.out.println("\n🔍 TESTING: " + symbol);

            // Setup historical data for this symbol
            setupCrossoverHistoricalData(symbol);

            // Check if crossover would occur
            boolean wouldCrossover = checkCrossoverCondition(symbol);

            if (wouldCrossover) {
                System.out.println("   ✅ WOULD GENERATE BUY SIGNAL");
                buySignalsGenerated++;

                // Actually execute the buy signal
                System.out.println("   🚀 EXECUTING BUY SIGNAL...");
                executeRealBuySignal(symbol);
            } else {
                System.out.println("   ⏸️  NO BUY SIGNAL - Crossover condition not met");
            }
        }

        System.out.println("\n📊 MULTIPLE INSTRUMENTS SUMMARY:");
        System.out.println("   Total Instruments Tested: " + testSymbols.length);
        System.out.println("   Buy Signals Generated: " + buySignalsGenerated);
        System.out.println("   Success Rate: " + (buySignalsGenerated * 100 / testSymbols.length) + "%");
    }

    /**
     * PRE-POPULATE HISTORICAL DATA to ensure buy signals are generated
     */
    private void prePopulateHistoricalData() throws Exception {
        System.out.println("📥 PRE-POPULATING HISTORICAL DATA FOR BUY SIGNALS...");

        String ceSymbol = "NFO:NIFTY25D0226250CE";
        String peSymbol = "NFO:NIFTY25D0226250PE";

        // Clear any existing data
        clearHistoricalData();

        // Setup historical data for PERFECT VWAP CROSSOVER conditions
        // Historical pattern: Previous candles below VWAP, current candle above VWAP

        // For CE Option: 101.75 premium
        System.out.println("\n📊 SETTING UP CE OPTION HISTORICAL DATA:");
        // Candle 1 (oldest): Below VWAP
        updateHistoricalData(ceSymbol, 99.50, 101.0, "CE - Candle 1 - Below VWAP");
        // Candle 2: Below VWAP
        updateHistoricalData(ceSymbol, 100.25, 101.5, "CE - Candle 2 - Below VWAP");
        // Candle 3 (previous): Below VWAP - SETUP FOR CROSSOVER
        updateHistoricalData(ceSymbol, 101.25, 102.0, "CE - Candle 3 - Below VWAP (Crossover Setup)");
        // Candle 4 (current): Above VWAP - TRIGGER CROSSOVER
        updateHistoricalData(ceSymbol, 102.75, 102.0, "CE - Candle 4 - Above VWAP (Crossover Trigger)");

        // For PE Option: 113.65 premium
        System.out.println("\n📊 SETTING UP PE OPTION HISTORICAL DATA:");
        // Candle 1 (oldest): Below VWAP
        updateHistoricalData(peSymbol, 110.50, 112.0, "PE - Candle 1 - Below VWAP");
        // Candle 2: Below VWAP
        updateHistoricalData(peSymbol, 111.75, 113.0, "PE - Candle 2 - Below VWAP");
        // Candle 3 (previous): Below VWAP - SETUP FOR CROSSOVER
        updateHistoricalData(peSymbol, 112.85, 114.0, "PE - Candle 3 - Below VWAP (Crossover Setup)");
        // Candle 4 (current): Above VWAP - TRIGGER CROSSOVER
        updateHistoricalData(peSymbol, 114.65, 114.0, "PE - Candle 4 - Above VWAP (Crossover Trigger)");

        System.out.println("✅ HISTORICAL DATA PRE-POPULATED FOR BUY SIGNAL GENERATION");
    }

    private void setupPerfectCrossoverData(String symbol, double currentPrice, double currentVWAP) throws Exception {
        System.out.println("🔧 Setting up perfect crossover data for: " + symbol);

        // Setup historical pattern: All previous below VWAP, current above VWAP
        double basePrice = currentPrice * 0.97; // Start 3% below

        // Previous candles (all below their respective VWAPs)
        for (int i = 1; i <= 3; i++) {
            double historicalPrice = basePrice + (i * 0.5);
            double historicalVWAP = historicalPrice + 1.0; // VWAP always above price
            updateHistoricalData(symbol, historicalPrice, historicalVWAP,
                    "Candle " + i + " - Below VWAP (Setup)");
        }

        // Current candle (above VWAP - triggers crossover)
        updateHistoricalData(symbol, currentPrice, currentVWAP,
                "Current - Above VWAP (Crossover Trigger)");
    }

    private void ensureHistoricalData(String symbol) throws Exception {
        Method hasSufficientDataMethod = historicalDataManager.getClass().getMethod("hasSufficientData", String.class);
        boolean hasData = (Boolean) hasSufficientDataMethod.invoke(historicalDataManager, symbol);

        if (!hasData) {
            System.out.println("⚠️  Adding historical data for: " + symbol);
            setupCrossoverHistoricalData(symbol);
        }
    }

    private void setupCrossoverHistoricalData(String symbol) throws Exception {
        // Generate realistic historical data that will trigger crossover
        Random random = new Random();
        double basePrice = 100 + random.nextDouble() * 30; // Random base price

        // Create 3 historical candles all below VWAP
        for (int i = 0; i < 3; i++) {
            double price = basePrice - (3 - i) + (random.nextDouble() * 2 - 1);
            double vwap = price + 1.5 + (random.nextDouble() * 1); // VWAP above price
            updateHistoricalData(symbol, price, vwap, "Historical Candle " + (i+1));
        }

        // Current candle above VWAP (triggers crossover)
        double currentPrice = basePrice + 2 + (random.nextDouble() * 2);
        double currentVWAP = currentPrice - 1 - (random.nextDouble() * 1); // VWAP below price
        updateHistoricalData(symbol, currentPrice, currentVWAP, "Current Candle - Crossover");
    }

    private boolean checkCrossoverCondition(String symbol) throws Exception {
        Method hasSufficientDataMethod = historicalDataManager.getClass().getMethod("hasSufficientData", String.class);
        boolean hasData = (Boolean) hasSufficientDataMethod.invoke(historicalDataManager, symbol);

        if (!hasData) {
            System.out.println("   ❌ Insufficient historical data");
            return false;
        }

        // Get previous candle
        Method getPreviousCandleMethod = historicalDataManager.getClass().getMethod("getPreviousCandle", String.class);
        Object previousCandle = getPreviousCandleMethod.invoke(historicalDataManager, symbol);

        // Get current candle
        Method getCurrentCandleMethod = historicalDataManager.getClass().getMethod("getCurrentCandle", String.class);
        Object currentCandle = getCurrentCandleMethod.invoke(historicalDataManager, symbol);

        if (previousCandle == null || currentCandle == null) {
            return false;
        }

        // Extract data
        Class<?> candleClass = previousCandle.getClass();
        Method getCloseMethod = candleClass.getMethod("getClose");
        Method getVWAPMethod = candleClass.getMethod("getVWAP");

        double previousPrice = (Double) getCloseMethod.invoke(previousCandle);
        double previousVWAP = (Double) getVWAPMethod.invoke(previousCandle);
        double currentPrice = (Double) getCloseMethod.invoke(currentCandle);
        double currentVWAP = (Double) getVWAPMethod.invoke(currentCandle);

        // Check crossover condition
        boolean crossover = (previousPrice < previousVWAP) && (currentPrice > currentVWAP);

        System.out.println("   Previous: Price(" + previousPrice + ") " +
                (previousPrice < previousVWAP ? "<" : ">=") + " VWAP(" + previousVWAP + ")");
        System.out.println("   Current:  Price(" + currentPrice + ") " +
                (currentPrice > currentVWAP ? ">" : "<=") + " VWAP(" + currentVWAP + ")");

        return crossover;
    }

    private void updateHistoricalData(String symbol, double price, double vwap, String description) throws Exception {
        Method updateMethod = historicalDataManager.getClass().getMethod(
                "updateHistoricalData", String.class, double.class, double.class);
        updateMethod.invoke(historicalDataManager, symbol, price, vwap);

        System.out.println("   " + description + " | Price: " + price + " | VWAP: " + vwap +
                " | " + (price < vwap ? "📉 BELOW" : "📈 ABOVE"));
    }

    private void clearHistoricalData() throws Exception {
        Method clearMethod = historicalDataManager.getClass().getMethod("clearData");
        clearMethod.invoke(historicalDataManager);
        System.out.println("🧹 Cleared existing historical data");
    }

    private void verifyHistoricalData() throws Exception {
        System.out.println("\n🔍 VERIFYING HISTORICAL DATA...");

        String[] testSymbols = {"NFO:NIFTY25D0226250CE", "NFO:NIFTY25D0226250PE"};

        for (String symbol : testSymbols) {
            Method hasSufficientDataMethod = historicalDataManager.getClass().getMethod("hasSufficientData", String.class);
            boolean hasData = (Boolean) hasSufficientDataMethod.invoke(historicalDataManager, symbol);
            System.out.println("   " + symbol + " - Sufficient Data: " + (hasData ? "✅ YES" : "❌ NO"));
        }
    }

    private void verifyBuySignalsGenerated() {
        System.out.println("\n🎯 VERIFYING BUY SIGNALS GENERATED...");

        if (!executedSignals.isEmpty()) {
            System.out.println("✅ SUCCESS: " + executedSignals.size() + " buy signals generated:");
            for (String signal : executedSignals) {
                System.out.println("   🚀 " + signal);
            }
        } else {
            System.out.println("❌ FAILED: No buy signals generated");
            System.out.println("   Check historical data setup and market conditions");
        }
    }

    private void verifyMultipleBuySignals() {
        System.out.println("\n🎯 VERIFYING MULTIPLE BUY SIGNALS...");

        long ceSignals = executedSignals.stream().filter(s -> s.contains("CE")).count();
        long peSignals = executedSignals.stream().filter(s -> s.contains("PE")).count();

        System.out.println("   CE Signals: " + ceSignals);
        System.out.println("   PE Signals: " + peSignals);
        System.out.println("   Total Signals: " + executedSignals.size());

        if (ceSignals > 0 && peSignals > 0) {
            System.out.println("✅ EXCELLENT: Both CE and PE signals generated!");
        } else if (executedSignals.size() > 0) {
            System.out.println("✅ GOOD: " + executedSignals.size() + " signals generated");
        } else {
            System.out.println("❌ POOR: No signals generated");
        }
    }

    // Existing methods from previous implementation (keep these)
    private void executeRealTradingCycle() throws Exception {
        System.out.println("🔄 EXECUTING COMPLETE TRADING CYCLE...");
        Method executeTradingCycleMethod = VWAPOptionsStrategy.class.getDeclaredMethod("executeTradingCycle");
        executeTradingCycleMethod.setAccessible(true);
        executeTradingCycleMethod.invoke(strategy);
        System.out.println("✅ TRADING CYCLE EXECUTION COMPLETED");
    }

    private Map<String, String> findRealOptions() throws Exception {
        Method findOptionsMethod = VWAPOptionsStrategy.class.getDeclaredMethod("findOptionsNearTargetPrice");
        findOptionsMethod.setAccessible(true);
        @SuppressWarnings("unchecked")
        Map<String, String> selectedOptions = (Map<String, String>) findOptionsMethod.invoke(strategy);
        return selectedOptions;
    }

    private Map<String, Boolean> analyzeVWAPCrossovers(List<String> instruments) throws Exception {
        Method analyzeMethod = batchVWAPAnalyzer.getClass().getMethod("analyzeVWAPCrossovers", List.class);
        @SuppressWarnings("unchecked")
        Map<String, Boolean> results = (Map<String, Boolean>) analyzeMethod.invoke(batchVWAPAnalyzer, instruments);
        return results;
    }

    private void executeRealBuySignal(String instrument) throws Exception {
        System.out.println("🚀 EXECUTING BUY SIGNAL FOR: " + instrument);
        Method executeBuySignalMethod = VWAPOptionsStrategy.class.getDeclaredMethod("executeBuySignal", String.class);
        executeBuySignalMethod.setAccessible(true);
        executeBuySignalMethod.invoke(strategy, instrument);
        executedSignals.add(instrument);
        System.out.println("✅ BUY SIGNAL EXECUTION COMPLETED");
    }

    @Test
    @DisplayName("FINAL SUMMARY: Historical Data Buy Signal Results")
    void finalHistoricalDataSummary() {
        System.out.println("\n📊 FINAL HISTORICAL DATA BUY SIGNAL SUMMARY");
        System.out.println("===========================================");
        System.out.println("Execution Time: " + new Date());
        System.out.println("Total Buy Signals Executed: " + executedSignals.size());

        if (!executedSignals.isEmpty()) {
            System.out.println("\n✅ SUCCESSFULLY EXECUTED BUY SIGNALS:");
            for (String instrument : executedSignals) {
                System.out.println("   📈 " + instrument);
            }
            System.out.println("\n🎯 VWAP STRATEGY IS WORKING CORRECTLY!");
        } else {
            System.out.println("\n❌ NO BUY SIGNALS EXECUTED");
            System.out.println("   Check historical data population and crossover conditions");
        }
    }
}