# Zerodha API Configuration
zerodha.api.key=e85ngsrd7lekw61v
zerodha.api.secret=oqm11fvqp3rwdsvbwicaeo5jpahizvzk
zerodha.access.token=LLXdnL8oOog0s4bxTDxhzxH0Qy08A3i5
zerodha.api.baseurl=https://api.kite.trade

# Trading Strategy Configuration
trading.risk.per.trade=1000
trading.stop.loss.percentage=0.1
trading.target.percentage=0.04
trading.max.positions=5
trading.lot.size=75

# Instruments to Track
trading.instruments=NSE:NIFTY 50
nifty50.symbol=NSE:NIFTY 50

# Trading Schedule
trading.start.time=09:15
trading.end.time=15:15
trading.interval.time=5

# Risk Management
max.daily.loss=52000

# VWAP Strategy Configuration
vwap.period=50
option.target.price=100.0

# VWAP Options Strategy Configuration
vwap.options.target.price=100.0
vwap.options.price.tolerance=40.0
vwap.options.lot.size=650
vwap.options.max.positions=2
vwap.options.stoploss.multiplier=2.0
vwap.options.vwap.period=20

# Buying Hours Configuration (for VWAP Strategy)
buying.start.time=09:45
buying.end.time=15:15

